<?php

namespace app\common\controller;

use think\Controller;

class Base extends Controller
{
    public $code = 200;
    public $error = false;
    public $data = [];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Methods:*');
        header('Access-Control-Allow-Headers:x-requested-with,content-type');
    }

    /**
     * 空操作
     * @param $name
     * @return mixed
     */
    public function _empty($name)
    {
        $message = '请求异常#' . $name;
        $this->returnText($message, [], 404);
    }

    public function returnText($data = [],$error = null, $code = null)
    {
        $array = [
            'status' => empty($code) ? $this->code : $code,
            'error' => empty($error) ? $this->error : $error,
            'data' => $data ? $data : $this->data
        ];
        return json($array)->code($code);
    }

    public function exception($data = [],$error = null, $code = null)
    {
        $array = [
            'code' => empty($code) ? $this->code : $code,
            'error' => empty($error) ? $this->error : $error,
            'data' => $data ? $data : $this->data,
        ];
        throw new \app\common\controller\lib\BaseException($array);
    }

}